baseURL = "http://mac.into.sh/"
languageCode = "en-ca"
title = "mac.into.sh"
theme = "etch"
pygmentsCodeFences = true

[permalinks]
    posts = "/:slug/"

[author]
    name = "Geoff MacIntosh"

[markup.goldmark.renderer]
    unsafe = true
