baseURL = "https://mac.into.sh/"
languageCode = "en-ca"
title = "mac.into.sh"
enableRobotsTXT = true

pygmentsCodeFences = true
pygmentsUseClasses = true

enableGitInfo = true

[params]
    highlight = true

[permalinks]
    posts = "/:slug/"

[author]
    name = "Geoff MacIntosh"

[markup.goldmark.renderer]
    unsafe = true

disableKinds = ["taxonomy", "taxonomyTerm", "section", "page"]
