[build]
    publish = "public/"
    command = "hugo --gc --minify"

[context.production.environment]
    HUGO_VERSION = "0.71.0"
    HUGO_ENV = "production"

[[redirects]]
    from = "https://into.sh/*"
    to = "https://mac.into.sh/:splat"
    status = 301
    force = true

[[plugins]]
    package = "netlify-plugin-submit-sitemap"
    [plugins.inputs]
    baseUrl = "https://mac.into.sh"
    sitemapPath = "/sitemap.xml"
