name: Broken Link Checker

on:
  push:
    branches:
      - main

jobs:
  broken_link_checker_job:
    runs-on: ubuntu-latest
    name: Check for broken links
    steps:
    - name: Check for broken links
      id: link-report
      uses: elliotforbes/broken-link-checker@1.0.3
      with:
        url: 'https://mac.into.sh'
